Operaciones Básicas
Krono-Studios/tutorial-c-sharp pull request #26
Opened 2022-08-05 16:58 UTC by EstefanyCanul

Añadí el archivo Operaciones Básicas.

2022-08-05 19:14 UTC, EstebanBrito commented on OperacionesBasicas.md
> +# **Operaciones Básicas en C#**
No es necesario el uso de negritas en títulos. El "#" ya se encarga de eso.

2022-08-05 19:15 UTC, EstebanBrito commented on OperacionesBasicas.md
> +C# proporciona operadores. Compatibles con tipos incorporados y operaciones básicas, incluyendo los siguientes grupos:
Aquí me debes explicar qué es un operador en general y para qué sirven en programación.

2022-08-05 19:18 UTC, EstebanBrito commented on OperacionesBasicas.md
> +
Aquí viene bien que pongas viñetas listando los tipos de operadores, en plan:

* Operadores aritméticos
* Operadores bla bla bla
* Etc.

2022-08-05 19:18 UTC, EstebanBrito commented on OperacionesBasicas.md
> +Operaciones aritmeticas con operandos númericos.
Explica qué es un operador aritmético, para qué funcionan y cómo se diferencían de otros tipos de operadores.

2022-08-05 19:19 UTC, EstebanBrito commented on OperacionesBasicas.md
> +* Operando unarios: ++ (incremento), -- (decremento), + (más) y - (menos)
Esto manéjalo como título de tercer nivel (es decir, ###)

2022-08-05 19:21 UTC, EstebanBrito commented on OperacionesBasicas.md
> +    * Más (+): devuelve el valor se su operando.
Esto manéjalo como título de cuarto nivel. La razón de todo esto es que las viñetas se usan para listas cortas sin separaciones. Tú estás describiendo cada opción con ejemplos y todo, así que se ven feas las separaciones entre cada viñeta, es mejor usar títulos de menor nivel para indicar jerarquías.

2022-08-05 19:22 UTC, EstebanBrito commented on OperacionesBasicas.md
> +        Console.WriteLine(-b);
No podías simplemente poner "-a" en el WriteLine?

2022-08-05 19:22 UTC, EstebanBrito commented on OperacionesBasicas.md
> +* Operadores binarios: * (multiplicación), / (división), % (resto), + (suma) y - (resta)
Misma observación con los títulos aquí: maneja tercer y cuarto nivel.

2022-08-05 19:23 UTC, EstebanBrito commented on OperacionesBasicas.md
> +* Operando unarios: ++ (incremento), -- (decremento), + (más) y - (menos)
Además, es Operandos*

2022-08-05 19:24 UTC, EstebanBrito commented on OperacionesBasicas.md
> +    Use **float**, **double** o **decimal** para obtener el cociente de los dos operandos como número de punto flotante.
Proporciona un ejemplo de este caso de división.

2022-08-05 19:25 UTC, EstebanBrito commented on OperacionesBasicas.md
> +    Use el operador (+) para **concatenar cadenas** y **delegados**.
Agrega un ejemplo de esta aplicación del +

2022-08-05 19:25 UTC, EstebanBrito commented on OperacionesBasicas.md
> +## Operadores de asignación:
Pon una pequeña descripción de a qué te refieres con "asignación".

2022-08-05 19:26 UTC, EstebanBrito commented on OperacionesBasicas.md
> +  * Asignación simple (=): almacena el valor del segundo operando en el objeto especificado por el primer operando.
Todas estas 3 opciones necesitan al menos un ejemplo cada una

2022-08-05 19:26 UTC, EstebanBrito commented on OperacionesBasicas.md
> +
Te olvidaste que también existen las asignaciónes de suma (+=) y de división (/=)

2022-08-05 19:27 UTC, EstebanBrito commented on OperacionesBasicas.md
> +Operaciones lógicas con los operandos bool:
Aquí también debes explicar algo sobre operadores lógicos, para qué funcionan y cómo se difernecpian de los demás tipos de operadores.

2022-08-05 19:29 UTC, EstebanBrito commented on OperacionesBasicas.md
> +  * Operador unario (negación lógica).
Igualmente, los operadores de aquí necesitan ejemplos

2022-08-05 19:29 UTC, EstebanBrito commented on OperacionesBasicas.md
> +  * Operadores binarios (AND lógico), (OR lógico) y (OR exclusivo lógico).
Estos operandos los puedes omitir, no nos interesan los lógicos, sólo los lógico condicionales (||, &&)

2022-08-05 19:30 UTC, EstebanBrito commented on OperacionesBasicas.md
> +    * OR lógico condicional (||): calculoa el operador OR lógico de sus operandos.
calcula*

2022-08-05 19:31 UTC, EstebanBrito commented on OperacionesBasicas.md
> +    Genera true, si el operando se evalúa como false, y false, si el operando se evalúa como true.
Te faltó hablar del operador ternario (a?b:c)

2022-08-05 19:34 UTC, EstebanBrito requested changes
Cubres casi todos los temas necesarios, pero es necesario agregar ciertas cosas el archivo para que parezca un tutorial y no una hoja de apuntes. Y ni hablar de que te dió flojera y no pusiste ejemplos para los operandos de último.

Haz cambios necesarios y me avisas cuando puede revisar el PR otra ve0 @EstefanyCanul. Recuerda usar Conventional Commits en las descripciones de tus commits.

2022-08-06 04:55 UTC, EstefanyCanul commented on OperacionesBasicas.md
> +        Console.WriteLine(-b);
Ni tú ni yo jajaja, corregido.

2022-08-06 04:55 UTC, EstefanyCanul commented on OperacionesBasicas.md
> +    Use el operador (+) para **concatenar cadenas** y **delegados**.
Es el que dice suma, pero agregue otro.

2022-08-06 04:55 UTC, EstefanyCanul commented on OperacionesBasicas.md
> +
En mi asignación sólo decía esto: Operaciones de asignación (=, *=, -=) xd

2022-08-06 04:55 UTC, EstefanyCanul commented on OperacionesBasicas.md
> +    Genera true, si el operando se evalúa como false, y false, si el operando se evalúa como true.
En mi asignación sólo decía esto x2: Otros operadores (?:), y ese cuando lo agregaste? xd

2022-08-06 19:41 UTC, EstebanBrito commented on OperacionesBasicas.md
> +**2. Código:**
Quita ese ejemplo. Ya explicas bien el operando en el primer ejemplo.

2022-08-06 19:43 UTC, EstebanBrito commented on OperacionesBasicas.md
> +#### Suma (+): calcula la suma de sus operandos.
Agrega también para qué sirve cuando los operandos son cadenas.

2022-08-06 19:44 UTC, EstebanBrito commented on OperacionesBasicas.md
> +#### Asignación compuesta: (*=): multiplica ambos valores de los operandos.
Añade "...y luego almacena el resultado en la variable del primer operando"

2022-08-06 19:45 UTC, EstebanBrito commented on OperacionesBasicas.md
> +#### Asignación de división (/=): divide ambos valores de los operandos.
Mismo come tario awuí

2022-08-06 19:45 UTC, EstebanBrito commented on OperacionesBasicas.md
> +#### Asignación de resta (-=): resta ambos valores de los operandos.
Mismo comentario. Igual para la suma.

2022-08-06 19:45 UTC, EstebanBrito commented on OperacionesBasicas.md
> +#### Asignación de suma (+=): divide ambos valores de los operandos.
Suma* ambos valires...

2022-08-06 19:46 UTC, EstebanBrito commented on OperacionesBasicas.md
> +
Vale, discpa. Se me olvidó pactualizar el issue.

2022-08-06 19:46 UTC, EstebanBrito commented on OperacionesBasicas.md
> +Los operadores lógicos booleanos son **palabras** o **símbolos** se utilizan para conectar de forma lógica conceptos o grupos de términos de tipo bool.
que* se utilizan

2022-08-06 19:47 UTC, EstebanBrito commented on OperacionesBasicas.md
> +Los operadores lógicos booleanos son **palabras** o **símbolos** se utilizan para conectar de forma lógica conceptos o grupos de términos de tipo bool.
No se utilizan para conectar, sino para realizar operaciones de tipo lógica sobre sus operandis.

2022-08-06 19:48 UTC, EstebanBrito commented on OperacionesBasicas.md
> +  bool x = false && SecondOperand();
Quita eso de SecondOperand y sustitúyelo por una constante booleana (true o false, la que quieras)

2022-08-06 19:49 UTC, EstebanBrito commented on OperacionesBasicas.md
> +  bool x = true || SecondOperand();
Igual aquí, quita el secondOperand

2022-08-06 19:49 UTC, EstebanBrito commented on OperacionesBasicas.md
> +Genera true, si x y y se evalúa como true, y false, si x se evalúa como true y y como false.
Dónde están x y y? Cambia la redacción a "primer y segundo operando"

2022-08-06 19:50 UTC, EstebanBrito commented on OperacionesBasicas.md
> +Genera true, si x y y se evalúa como true, y false, si x se evalúa como true y y como false.
Igual aquí, no has referencia a x y y si no están declarados. Puedes referenciar al primer y segundo operando, o al operando izq/derecho

2022-08-06 19:51 UTC, EstebanBrito commented on OperacionesBasicas.md
> +  Console.WriteLine(x !passed);
Quita el x

2022-08-06 19:53 UTC, EstebanBrito commented on OperacionesBasicas.md
> +**Código:**
No hagas uso de funciones. Ese tema se ve después de operandos, y un lector novato no sabría qué estás haciendo en el ejemplo si desconoce qué son las funciones.
Mejor redacta tu propio ejemplo, a ver si entendiste el operador terciario.

2022-08-06 19:54 UTC, EstebanBrito requested changes
Se ve mejor, pero hace falta pulir ciertos detallitos. Avísame cuando ya pueda revisar de nuevo @EstefanyCanul .

2022-08-07 18:38 UTC, EstebanBrito approved these changes
La verdad es que no revisé el PR a profundidad. Aprobé los cambios para que pasemos a otra fase de la actividad. Estáte pendiente de la siguiente issue que te toque.

2022-08-07 18:39 UTC, merged