Freature/BAS-006
Krono-Studios/tutorial-c-sharp pull request #27
Opened 2022-08-05 23:04 UTC by ElaiaWood

## Investigación acerca de los delegado en C#

La siguiente investigación con el nombre de archivo "Delegados.md" fue realizada para explicar una definición, sintaxis para definirlo, así como diferentes ejemplos del uso de los delegado en C#; lo mismo para las expresiones *lambda*, pero aplicado para los delegados.

Se realizó un total de 2 commits en la que se dividió la investigación en
* Delegados y su aplicación
* Funciones *lambda*

El trabajo fue elaborado por: Elias X. Feria en la rama "freature/BAS-006"

2022-08-06 17:23 UTC, EstebanBrito commented
La rama es feature, no freature XD

2022-08-06 17:24 UTC, EstebanBrito commented
Qué genial pusiste la descripción de tu PR. Te voy a usar como buen ejemplo 👀

2022-08-06 17:35 UTC, EstebanBrito commented
No agregues nada en la sección "Projects" del PR. Sólo agrega el issue en la sección "Development" y ya.

2022-08-06 17:36 UTC, EstebanBrito commented on Delegados.md
> +Delegados en C#
Se te pasó el #

2022-08-06 17:36 UTC, EstebanBrito commented on Delegados.md
> +## Definicion
Definición*

2022-08-06 17:46 UTC, EstebanBrito commented on Delegados.md
> +Se define como un tipo que permite declarar una variable/argumentos que apunta a otro método; siendo esto una referencia a otro método cualquiera que sea **compatible**, encapsulandolo de forma segur
Entienda la idea, pero no me gusta la redacción. Parafrasea para que queden claros las siguintes cosas:
* "Se define como un tipo": ¿Un tipo de qué?
* "una variable/argumentos que apunta a otro método": Para que exista un "otro" método, entonces es porque ya existía uno, ¿no?
* "siendo esto": No me queda claro a qué se refiere "esto". ¿Al tipo, al otro método?
* "otro método cualquiera que sea compatible": ¿Cómo sabes si un método es compatible o no?
* encapsulandolo de forma segura: Primero, ta falta un acento. No utilices la palabra encapsulamiento puesto que el término ya se utiliza para refrenciar a otro concepto de programación. Si lo uses indiscriminadamente, generarás confusión.

2022-08-06 17:49 UTC, EstebanBrito commented on Delegados.md
> +> Un delegado es un objeto que contiene una referencia a un método.
Me gustan este tipo de líneas. Son como un TL;DR de párrafo anteriores.

2022-08-06 17:50 UTC, EstebanBrito commented on Delegados.md
> +Hay que tener en cuenta algunas cosas acerca de los **delegados**
Faltan los dos puntos al final

2022-08-06 17:51 UTC, EstebanBrito commented on Delegados.md
> +* **compatible**: El método que apunta el delegado debe compartir el mismo tipo de retorno y tipo de parametros declarados previamente. No tienen que coincidir los nombres.
El método al que apunta*

2022-08-06 17:54 UTC, EstebanBrito commented on Delegados.md
> +* **compatible**: El método que apunta el delegado debe compartir el mismo tipo de retorno y tipo de parametros declarados previamente. No tienen que coincidir los nombres.
parámetros*

2022-08-06 17:58 UTC, EstebanBrito commented on Delegados.md
> +## Declaración
Esta sección está bien

2022-08-06 17:58 UTC, EstebanBrito commented on Delegados.md
> +1. En una clase, declaremos un delegado de tipo entero con dos parametros del mismo.
parámetros* Y corrige todas las faltas de orotgrafía que tengas en la redacción, porfa.

2022-08-06 18:06 UTC, EstebanBrito commented on Delegados.md
> +3.  Ahora veremos la forma convencional del llamado de una función y en como llamara a traves del delegado. Recordemos que, para el llamado de una función es necesario crear un objeto
Con este ejemplo tengo muchos comentarios que dar.
* Primero, me parece demasiado largo. Un ejemplo debe enfocarse a explicar un concepto en particular, y depurar todo aquello que no ayude a explicar tal cosa. Recomiendo saltarte los pasos 1-3 y presentar el código completo de la sección 3.2.
* Segundo, no añadas objetos ni cosas de POO en el ejemplo. Recuerda que el posible lector no está familiarizado con esos temas.
* Tercero, revisa el sig comentario...
* Segund

2022-08-06 18:10 UTC, EstebanBrito commented on Delegados.md
> +                    Operar objDelegado = objeto.sumar;
Aquí correctamente defines una variable del tipo delegado "Operar", y le asignas una función compatible. Hasta ahí todo bien.
¿Pero por qué rayos llamas a delegado() en el WriteLine y no a objDelegado? "delegado" ni siquiera establa declarado en ningún lugar. No tiene sentido el ejemplo.

2022-08-06 18:10 UTC, EstebanBrito commented on Delegados.md
> +## Lamda
Funciones Lambda*

2022-08-06 18:19 UTC, EstebanBrito commented on Delegados.md
> +        class Programa
Cuando usas ejemplos de código, englóbalos usando bloques de código de Markdown, así:
 ```c#
public void Main(string[] args){
    Console.WriteLine("Hola, Eláas");
```

2022-08-06 18:21 UTC, EstebanBrito commented on Delegados.md
> +Algo a tomar en cuenta es que los delegados que vayamos a crear pueden recibir un nombre, pero también existe opción de ser un **método anonimo**. Un tipo de delegado que permite pasar un bloque de c
Cambia método por función. Un método es un tipo de función específica, aquella ligada a objetos y clases. Pero las funciones pueden anónimas sin importar si son métodos o no.

2022-08-06 18:23 UTC, EstebanBrito commented on Delegados.md
> +        delegate in ejemploDelegado(int x, int y);
int*

2022-08-06 18:23 UTC, EstebanBrito commented on Delegados.md
> +        ejemnploDelegado objetoDelegado = (x, y) => x * y;
ejemplo*

2022-08-06 18:23 UTC, EstebanBrito commented on Delegados.md
> +        ejemnploDelegado objetoDelegado = (x, y) => x * y;
Buen ejemplo de funciones lambda, por cierto.

2022-08-06 18:36 UTC, EstebanBrito commented on Delegados.md
> +## Ejemplo
Deja sólo este ejemplo. Es más completo que el anterior.

2022-08-06 18:49 UTC, EstebanBrito requested changes
Cubres bastantes puntos del tema, pero o los ejemplos están demasiado extensos o la redacción es confusa. Yo sé que conoces el tema, pero me interesa saber si puedes explicarlo de forma concisa y clara. Sólo así sabré si dominas el tema y podemos pasar a otros.

Lee los comentarios que te dejé, realiza cambios y avísame cuando el PR esté listo para revisión de nuevo @ElaiaWood

2022-08-17 05:26 UTC, ElaiaWood commented
Investigación acerca de los delegado en C#

Corrección del archivo Delegate.md

2022-08-30 14:17 UTC, EstebanBrito approved these changes
La verdad, no revisé a profundidad tu PR, pero lo acepto porque debemos seguir con la actividad.

2022-08-30 14:18 UTC, merged